---
title: "Notebook for generating PATT Estimations"
output: html_notebook
---

Import the common scripts, modules and libraries and set the working directory.

```{r}
setwd("/home/neehan/data/Nafis/ESCA_Git")
source("./Scripts/common.R")
source("./Scripts/run_patt_scenario.R")
source("./Modules/p_val_add.R")
source("./Modules/equity_metrics_miao.R")
```

Set hyperparameters.

```{r}
TA_World <- data %>% filter(RANDASSIGN==1)
TA_size <- 1000
total_seeds <- 20 #number of total scenarios
IPF_maxiter <- 100
step_size <- 100
randomization_ratio <- 1
num_col <- 7
CC_size_list <- seq(TA_size-step_size, 100, -step_size)
EC_size_list <- randomization_ratio*TA_size - CC_size_list
```

Generate and save results into the designated directory.

```{r}
#final dataframe that will contain the result
Final_PATT_Summary <- data.frame(matrix(ncol = num_col, nrow = 0))
colsPATT <- c("Seed", "CC_Size", "TA_CC", "TA_HC", "TA_HC_Prop", 
              "TA_HC_IPF", "TA_HC_Both")
colnames(Final_PATT_Summary) <- colsPATT

#settings for cluster initiation and parallelization
cores=detectCores(logical = TRUE) #check number of cores
cl <- makeCluster(cores[1]-1) #using all but one nodes
registerDoSNOW(cl) #register the cluster

packages <- c("dplyr", "ipfr", "MatchIt", "marginaleffects") #packages to copy in each node in the cluster

pb <- txtProgressBar(max = length(total_seeds * length(CC_size_list)), style = 3)
progress <- function(n) setTxtProgressBar(pb, n)
opts <- list(progress = progress)

#nested parallelization starts here
Final_PATT_Summary <- foreach(seed_value=seq(1,total_seeds,1), .combine = 'rbind', 
                              .packages = packages, 
                              .options.snow = opts) %:%
      foreach (size=CC_size_list, .combine = "rbind", .packages = packages) %dopar%{
                                   run_one_patt_scenario(seed_value, size)
  }

#close progress bar and turn off + release cluster
close(pb)
stopCluster(cl)
stopImplicitCluster()

#save the data
setwd("/home/neehan/data/Nafis/ESCA_Git")
directory <- "./Data/Results/M6/"
filename <- "PATT_Summary.csv"
write.csv(Final_PATT_Summary, paste(directory, filename, sep = ""), row.names = FALSE)
```
