---
title: "Notebook for generating equity summary data"
output: html_notebook
---

Import the common scripts, modules and libraries and set the working directory.

```{r}
setwd("/home/neehan/data/Nafis/ESCA_Git")
source("./Scripts/common.R")
source("./Scripts/run_ldm_scenario.R")
source("./Modules/p_val_add.R")
source("./Modules/equity_metrics_miao.R")
```

Set hyperparameters.

```{r}
TA_World <- data %>% filter(RANDASSIGN==1)
TA_size <- 1000
total_seeds <- 20
IPF_maxiter <- 100
step_size <- 100
randomization_ratio <- 1
num_col <- 10
CC_size_list <- seq(TA_size-step_size, 100, -step_size)
EC_size_list <- randomization_ratio*TA_size - CC_size_list
```

Generate and save results into the designated directory. It's going to take around 15\~18 minutes in total. The code keeps running for about 10 minutes even after the progress bar shows 100%. The progress bar is still little buggy and I'll fix it.

```{r}
Final_LDM_Summary <- data.frame(matrix(ncol = 10, nrow = 0))
colsLDM <- c("Seed", "CC_Size", "Var", "Level", "LDM_TA", "LDM_CC", "LDM_HC_Prop", "LDM_HC_IPF", 
             "LDM_TA_Prop_IPF", "LDM_HC_Prop_IPF" )
colnames(Final_LDM_Summary) <- colsLDM

cores=detectCores(logical = TRUE)
cl <- makeCluster(cores[1]-1) #not to overload your computer
registerDoSNOW(cl)

packages <- c("dplyr", "ipfr", "MatchIt", "marginaleffects")

pb <- txtProgressBar(max = length(total_seeds * length(CC_size_list)), style = 3)
progress <- function(n) setTxtProgressBar(pb, n)
opts <- list(progress = progress)

Final_LDM_Summary <- foreach(seed_value=seq(1,total_seeds,1), .combine = 'rbind', 
                             .packages = packages, 
                             .options.snow = opts)%:%
  foreach (size=CC_size_list, .combine = "rbind", .packages = packages) %dopar%{
    run_one_ldm_scenario(seed_value, size)
    }


close(pb)
stopCluster(cl)
stopImplicitCluster()

setwd("/home/neehan/data/Nafis/ESCA_Git")
directory <- "./Data/Results/M6/"
filename <- "LDM_Summary.csv"
write.csv(Final_LDM_Summary, paste(directory, filename, sep = ""), row.names = FALSE)
```
